#!/bin/bash

file='/var/spool/cron/crontabs/root'

checksum=`md5sum ${file}` 

check_checksum() {
  newsum=`md5sum ${file}` 
  if [[ $newsum != $checksum ]]; then
    echo "Someone modified ${file}" | mail -s 'alert cron' amathias63@gmail.com;
    checksum=$newsum;
  fi
}

while sleep 1;
do check_checksum
done
